---
development:
  cloud_name: meme-economy
  api_key: '185964598592431'
  api_secret: "-j25TpdmSZ8VcLHAdmFVjoo6aUM"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: meme-economy
  api_key: '185964598592431'
  api_secret: "-j25TpdmSZ8VcLHAdmFVjoo6aUM"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: meme-economy
  api_key: '185964598592431'
  api_secret: "-j25TpdmSZ8VcLHAdmFVjoo6aUM"
  enhance_image_tag: true
  static_image_support: false
