# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6dcf598747c2f22ae543908e5e5c806afc8cfda29fca7ffff737b31a539a6f0ad7a7ac2f8d5fb11f2aad1467ee8eb91b19ba642604c23589082a86ba7dc04d

test:
  secret_key_base: 396669f3632173306ebd872b2ba009628318597b5ee36b7ce50dcebd0eb6208cd8cb3cca1e861e8060c218ad5fc13ffe160f6da8203abcc94131687d9cf16c84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
